
#+SETUPFILE: org-html-styles/readtheorg/theme-readtheorg-local.setup

#+MACRO: course-name Стратегии коммерциализации инноваций

#+TITLE: Выполнение курсовой работы по дисциплине "{{{course-name}}}"
#+AUTHOR: Константин Моренко
#+EMAIL: vim@konstantin-morenko.ru
#+LANGUAGE: ru
#+OPTIONS: email:t

#+BEGIN_EXPORT html
<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(69954367, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/69954367" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
#+END_EXPORT

* Введение
  :PROPERTIES:
  :UNNUMBERED: t
  :CUSTOM_ID: intro
  :END:

Курсовая работа по дисциплине "{{{course-name}}}" является творческой
работой, в которой студент должен показать навыки и умение
вести анализ экономических понятий, делать самостоятельные выводы,
имеющие практическое значение.

** Онлайн-версия
   :PROPERTIES:
   :CUSTOM_ID: online
   :END:

#+begin_comment
- [ ] Переформулировать про устаревание методички
- [ ] Система контроля версий
#+end_comment

Данные методические указания представлены и в онлайн-виде на странице
https://konstantin-morenko.github.io/cw-innovations/.

Изданная методичка часто устаревает к следующему году.  В процессе
работы с ней обнаруживаются небольшие ошибки, мелкие доработки.  Сами
эти доработки не достаточно велики, чтобы из-за них делать следующее
издание.  Вместе с тем, они достаточно важны для организации процесса
обучения.

Кроме этого, что все эти идеи по доработке приходят не сразу, а
постепенно: сейчас одно, через две недели что-то другое.

Следуя непрерывному процессу улучшения качества, внедрять эти
разработки лучше как можно скорее после их обнаружения.  Но важно не
только исправить текст, но и довести до всех участников процесса новую
версию.  В случае с печатной версией методички сделать это трудно.

Размещенная онлайн методичка /всегда/ является самой новой и
актуальной версией работы.  Корректировки в нее вносятся относительно
просто и сразу отражаются на содержании.  Хотя такой подход имеет свои
трудности: нужно четко отслеживать изменения от версии к версие.
Хорошо организованная и прозрачная процедура изменений позволяет легко
реализовать этот процесс.

По мере накопления изменений номер версии будет увеличиваться.  Через
некоторое время, когда таких изменений накопится достаточно много,
можно готовить следующее издание.  А благодаря списку изменений легко
узнать, что же было доработано с момента прошлого издания.

* Основные требования к курсовой работе
  :PROPERTIES:
  :CUSTOM_ID: requirements
  :END:

Курсовая работа представляет собой разработку актуальной теоретической
или практической экономической проблемы.  В ней должны быть отражены
позиции российских и зарубежных экономистов, периодическая научная
литература, статистическая информация, материалы, взятые из сети
Internet.

Перед выполнением работы студент составляет план.  План служит опорой
и перечнем тем, которые студенту нужно раскрыть в ходе выполнения
курсовой работы.  Студент самостоятельно или консультируясь с
руководителем подбирает основную и дополнительную литературу,
определить те важнейшие публикации, которые будут положены в основу
курсовой работы и наиболее полно раскрывают тему.

Тема курсовой работы раскрывается на основе изучения современной
научной и учебной экономической литературы, журнальных и газетных
публикаций, статистических материалов.  Хотя отдельные главы и
параграфы курсовой работы могут совпадать с названием некоторых
параграфов соответствующих научных изданий или разделов учебников,
работа не должна быть пересказом материала, изложенного в литературе.

Не допускается дословное заимствование (списывание) текста.  Дословное
копирование литературы противоречит смыслу курсовой работы, не
способствует получению практических знаний и умений, приучает студента
к бездумному повторению известных истин.  Поэтому текст курсовой
работы должен быть написан самостоятельно в соответствии с планом.  В
работе должны содержаться элементы творчества, теоретические положения
должны быть связаны с практикой хозяйствования и реформирования
экономики.

В ходе написания работы студент изучает правила оформления научного
аппарата, грамотного применения сносок, ссылок на источники информации
и правил оформления списка литературы или библиографического списка.

Если в литературе по теме работы имеются различные точки зрения или
представлены различные методы решения той или иной проблемы, студент
должен обосновать свою позицию, которая, не обязательно должна
совпадать с чьим-то мнением.  При этом желательно, чтобы студент
продемонстрировал практическое подтверждение своей точки зрения.
Курсовая работа показывает способность студента самостоятельно
мыслить, творчески относиться к литературным источникам, формулировать
выводы и предложения, основанные на анализе фактического материала.

** Критерии оценки курсовой работы
   :PROPERTIES:
   :CUSTOM_ID: rating
   :END:

При проверке работы преподавателем оцениваются:

1. Знания и умения на уровне требований стандарта конкретной
   дисциплины, знание фактического материала, усвоение общих
   представлений, понятий, идей.

2. Характеристика реализации цели и задач исследования (новизна и
   актуальность поставленных в реферате проблем, правильность
   формулирования цели, определения задач исследования, правильность
   выбора методов решения задач и реализации цели; соответствие
   выводов решаемым задачам, поставленной цели, убедительность
   выводов).

3. Степень обоснованности аргументов и обобщений (полнота, глубина,
   всесторонность раскрытия темы, логичность и последовательность
   изложения материала, корректность аргументации и системы
   доказательств, характер и достоверность примеров, иллюстративного
   материала, широта кругозора автора, наличие знаний интегрированного
   характера, способность к обобщению).

4. Качество и ценность полученных результатов (степень завершенности
   реферативного исследования, спорность или однозначность выводов).

5. Использование литературных источников (соответствие характера
   источника целям цитирования, достоверность источника согласно цели
   цитирования).

6. Культура письменного изложения материала.

7. Культура оформления материалов работы.

8. Сроки выполнения отдельных этапов работы и срок сдачи работы.

Оценки выставляются согласно следующим положениям:

- отлично :: на основе глубоких знаний теории в работе дается
             самостоятельный анализ фактического материала, содержатся
             элементы научного творчества, делаются самостоятельные
             выводы и конкретные предложения.

- хорошо :: работа выполнена на высоком теоретическом уровне,
            достаточно полно освещаются вопросы темы, но отсутствует в
            должной степени самостоятельный подход к теме.

            В таких работах, как правило, выводы и предложения автор
            формулирует, исходя из теории и фактических примеров,
            взятых из литературных источников, нет анализа реальных
            случаев, нет относительно новых статистических данных по
            странам мира или по России.

- удовлетворительно ::  верно освещаются основные вопросы темы, но нет
     логически стройного изложения материала, отсутствуют творческий
     подход и самостоятельная оценка литературных и фактических
     источников, что не позволяет делать самостоятельные выводы и
     предложения.

     В таких работах могут встречаться ошибочные положения,
     стилистическая небрежность, неумелое оформление научного
     аппарата, устаревшие статистические и фактические данные.  Кроме
     того, оценкой удовлетворительно могут оцениваться работы,
     выполненные с нарушением установленных сроков сдачи.

- неудовлетворительно :: ставится в том случае, если работа допущена к
     защите, но на защите студент не может объяснить приведенные в
     работе положения и выводы, ответить на замечания руководителя.

     В этом случае часто автор не имеет отношения к выполнению работы.
     В случае получения оценки «неудовлетворительно» студент должен
     исправить замечания, разобраться в теме, внести в работу
     собственный вклад.

Получение на защите любой положительной оценки дает право на сдачу
экзамена по дисциплине.

* Этапы выполнения курсовой работы
  :PROPERTIES:
  :CUSTOM_ID: stages
  :END:

** Реферат (эссе)
   :PROPERTIES:
   :CUSTOM_ID: essay
   :END:

Перед выполнением курсовой работы студент должен ознакомиться с темой
работы в целом.  Написание реферата является первым этапом знакомства
с темой и служит отличной основой для дальнейшего написания курсовой
работы.  В ходе написания реферата по теме студент ищет источники
литературы и формирует свое представление о теме курсовой работы,
которое в дальнейшем служит основой для составления плана.

Процесс подготовки реферата состоит из двух частей:
1. Подготовка текста реферата
2. Защита реферата

Реферат по теме курсовой работы должен содержать (в скобках указан
/рекомендуемый объем/):
1. Титульный лист (1 страница).
2. Оглавление (1 страница).  В оглавлении указаны названия всех
   разделов (пунктов плана) реферата и номера страниц, указывающие
   начало этих разделов в тексте реферата.
3. Введение (1 страница).
4. Основная часть реферата (6 страниц), в которую рекомендуется
   включить 3--4 пункта, предполагает осмысленное
   и логичное изложение главных положений и идей, содержащихся в
   изученной литературе.  В тексте обязательны ссылки на
   первоисточники.  В том случае если цитируется или используется
   чья-либо неординарная мысль, идея, вывод, приводится какой-либо
   цифрой материал, таблицу --- обязательно сделайте ссылку на того
   автора у кого вы взяли данный материал.
5. Заключение (1 страница) содержит главные выводы, и итоги из текста
   основной части, в нем отмечается, как выполнены задачи и достигнуты
   ли цели, сформулированные во введении.
6. Список литературы (1 страница) здесь указывается реально
   использованная для написания реферата литература. Список
   составляется согласно правилам библиографического описания.

Объем реферата /не должен/ превышать 12 страниц.

В списке источников должно быть не меньше 3 источников.

Работа выполняется на одной стороне листа формата A4.  Рекомендуемый
размер шрифта --- 12, рекомендуемый междустрочный интервал --- 1,5.
Все листы реферата кроме титульного должны быть пронумерованы.

Порядок подготовки реферата тот же, то есть студент начинает с обзора
литературы.  Особенность подготовки реферата состоит в том, что эта
работа является подготовительной к выполнению курсовой работы, поэтому
студент в реферате только выполняет обзор литературы и высказывает
предположения.  Более детальная проработка вопроса выполняется им в
ходе курсовой работы.

Защита реферата происходит в устной форме после проверки реферата
преподавателем.  На защите студент кратко (в течение 2--3 минут)
излагает содержание реферата, после чего отвечает на вопросы
преподавателя.

** План выполнения работы
   :PROPERTIES:
   :CUSTOM_ID: work-plan
   :END:

Чтобы выполнить курсовую работу (выполнить --- написать, защитить и
получить оценку), студенту рекомендуется следовать этапам выполнения
курсовой работы.  Для успешного выполнения курсовой работы необходим
не только план курсовой работы, но и календарный план выполнения
работы.  Благодаря этому плану можно своевременно контролировать
прохождение контрольных точек и решать возникающие по ходу выполнения
трудности.  Срок выполнения каждого этапа указан в неделях от начала
семестра.

Для успешного выполнения курсовой работы необходимо:
- выбрать тему и утвердить ее у преподавателя:
  - результат: одобрение преподавателем выбранной темы;
  - срок: 4 неделя;
- подобрать необходимую научную, статистическую, справочную и учебную
  литературу:
  - результат: список источников литературы, на основании которых
    будет написана курсовая работа;
  - срок: 6 неделя;
- составить план курсовой работы:
  - результат: текстовый план курсовой работы с указанием планируемого
    количества страниц на каждый пункт);
  - срок: 8 неделя;
- раскрыть тему на основе изученной автором литературы с привлечением
  статистических данных и первичных материалов фирм, предприятий,
  бюджетных организаций, местных и федеральных органов власти, сделать
  выводы:
  - результат: текст курсовой работы;
  - срок: 3 контрольных точки, 10, 12 и 14 неделя;
- подготовиться к защите и защитить курсовую работу, то есть кратко
  рассказать суть работы, сформулировать выводы и предложения,
  показать знание изученной литературы:
  - результат: оценка за выполненную курсовую работу;
  - срок: 16 неделя.

** Выбор темы курсовой работы
   :PROPERTIES:
   :CUSTOM_ID: theme-selection
   :END:

Выбор темы курсовой работы осуществляется студентом по номеру
зачетки.  Если номер зачетки студента превышает общее количество тем,
то нужно продолжать перебирать темы с начала.

Студент вправе самостоятельно предложить собственную тему, если она
соответствует изучаемой дисциплине.  Для этого студент обосновывает
целесообразность изучения темы и согласует ее с руководителем.

Литературу для курсовой работы студент подбирает, работая с каталогами
литературы, с номерами экономических и финансовых журналов.

Основная научная литература должна быть представлена произведениями
наиболее видных современных российских и зарубежных экономистов.  К
основной литературе следует отнести также Гражданский кодекс РФ,
Налоговый кодекс РФ, Трудовой кодекс РФ, Федеральные Законы РФ о
различных видах хозяйственной деятельности, а также статистические
сборники по РФ и данные сайтов Интернет.  При подборе дополнительной
литературы необходимо обратить внимание на статьи и другие материалы в
журналах не старше 10 лет и газетах не старше 5 лет, издаваемых в
России и других странах.

Студенту не обязательно читать конкретный журнал или книгу целиком,
достаточно изучить отдельные статьи, разделы и главы, в которых
освещаются необходимые вопросы для выбранной темы курсовой работы.
Необходимую для чтения информацию дают аннотация книги, оглавление,
введение, заключение.

** Составление плана курсовой работы
   :PROPERTIES:
   :CUSTOM_ID: planning
   :END:

Результатом изучения литературы является составление плана курсовой
работы. Первоначально формируется краткий план, который затем
уточняется, что позволяет конкретизировать объект и предмет анализа,
составить окончательную структуру работы и разработать наиболее важные
тезисы по каждой главе и параграфу.

В план работы необходимо включить:
- введение;
- главы по наиболее значимым разделам темы (они перечислены в перечне
  тем);
- заключение (выводы);
- список литературы.

Например, план по теме «Роль золота в мировой валютной системе» может
выглядеть следующим образом:

- Введение
- Изменение роли золота в связи с эволюцией денег
  - Понятие полноценных денег и роль золота
  - Появление неполноценных бумажных денег и изменение роли золота
  - Три разновидности золотого монометаллизма: золотомонетного,
    золотослиткового и золотодевизного
- Международная торговля золотом и российский рынок золота
  - Роль и значение лондонского рынка золота
  - Роль других рынков золота
  - Российский рынок золота и состояние золотодобычи в РФ
- Заключение
- Список литературы

Структура курсовой работы уточняется при разработке ее плана и
согласовывается с руководителем.

** Подбор и обработка фактических и статистических материалов
   :PROPERTIES:
   :CUSTOM_ID: materials
   :END:

В раскрытии вопросов плана курсовой работы ключевую роль играют свежие
статистические материалы, данные конкретных предприятий.  Их
использование при написании работы углубляет понимание теоретических
положений, позволяет увидеть связь теории с практикой и реальной
экономической действительностью.

Подбор и осмысление, использование в курсовой работе конкретных
экономических материалов --- важный показатель уровня подготовки и
самостоятельности студента.  Основными источниками статистических
данных являются статистические сборники и справочники по Российской
Федерации, книги, журналы, отчеты предприятий, сайты Internet.

В ряде тем курсовых работ может быть необходимо использовать материалы
о производственной и коммерческой деятельности отдельных предприятий,
об экономике отрасли, города или области.  Это данные о коммерческой
деятельности предприятий, заработной плате и стимулировании труда, о
формировании издержек и прибыли, процента и ренты, о налогообложении,
о ценообразовании, о рекламной деятельности и др.  Главное назначение
таких материалов состоит в том, чтобы на фактах реальной экономической
жизни раскрыть освещаемые в работе теоретические положения,
использовать их как аргументы в пользу сделанных выводов.

Правильно подобранные статистические материалы позволяют составить
таблицы, рисунки в виде схем, диаграмм, помогающие проанализировать
экономические процессы.

При наличии большого объема статистического материала (например,
динамика инфляции за 10-15 лет во многих странах мира, платежные
балансы ряда стран, бухгалтерские балансы предприятий и другие
громоздкие таблицы) его следует поместить в приложение.

** Написание текста курсовой работы
   :PROPERTIES:
   :CUSTOM_ID: wr-text
   :END:

Студент может приступить к написанию текста работы после того, как
руководитель одобрил предложенный план курсовой работы.

Во введении автор обосновывает актуальности темы, определяет цель и
задачи.  Важное значение для введения имеет выбор методов анализа.
Если брать экономику в целом, то метод --- это путь к достижению
научных истин в анализе явлений и фактов, с помощью использования
различных приемов и способов анализа экономической действительности.

Самыми простыми методами анализа являются приемы формальной логики.
Она предлагает следующий путь доказательств.  Сначала автор выдвигает
тезис, затем подбираются аргументы и способы его доказательств.  Сами
способы могут быть прямыми с помощью графиков, рисунков, формул или
опытов.  Они могут быть и косвенными с помощью слов, убеждений,
сравнений, аналогий и т.д.  В курсовой работе могут встречаться оба
способа доказательств, с перевесом в пользу второго способа.

В каждой курсовой работе широко используется статистика или цифровые
данные экономических процессов.  Этот анализ называется статическим
методом.  Если на основе статистики строятся различные рисунки,
графики, диаграммы, то это используется графическийо метод.  Методы
анализа позволяют внести элементы упорядоченности, доказательности и
упорядоченности.

Особое место в методах анализа занимает моделирование, в том числе с
использованием Интернет.  Используемые компьютерные программы могут
основываться либо на теоретических моделях, либо на реальных
статистических данных, либо на объединении тех и других.  Под
моделированием понимается создание упрощенного аналога того или иного
явления и анализ его с помощью математических, графических или
компьютерных моделей.  Иногда модели могут быть и текстовые.

Дальше дается формулировка цели курсовой работы.  Исходя из целей
дальше перечисляются задачи курсовой работы.  Чаще всего решению
конкретных задач посвящены отдельные подразделы темы.  Кроме того,
можно сформулировать практическую значимость анализируемой темы.

Если по теме работы существуют различные позиции ученых или имеются
сведения о различных путях (способах) практического решения данной
проблемы, то студент должен определить свое отношение и обосновать
свою точку зрения, которая может совпадать с чьим-то мнением, или
может быть оригинальной и обновленной.  В последнем случае обоснование
должно быть развернутым, базироваться на теоретической основе и иметь
практическое подтверждение.

Если теория, на которой базируется тема работы, прошла определенные
этапы развития, претерпела определенные изменения, то в первой главе
эти моменты также должны найти свое отражение.  Для каждого параграфа
желательно подготовить рисунки, подтверждающие те или другие выводы
студента.  В конце главы или по ходу ее анализа должны быть
обязательно выводы студента, которые затем перейдут в заключение.

Первая глава служит общим обзором рассматриваемой темы и вводит
читателя в основные положения, которые далее будут использованы в
работе.  Необходимо также определить значение данной проблемы (темы
работы) в реализации экономической политики государства.

Во второй главе следует детально рассмотреть вопрос, которому
посвящена курсовая работа.  В качестве пунктов в этом разделе
используются те же пункты, которые приведены в задании к курсовой
работе для каждой из тем.

Заключение по работе пишется в виде выводов, полученных в ходе
выполнения работы.  В нем отражается решение поставленных задач и
полученных результатов.  Без промежуточных выводов в тексте работы
заключение часто бывает слабым, а это снижает общую оценку всей
курсовой работы.

Затем оформляется список использованной литературы, и если имеются
приложения, то дается от 1 до 5 приложений.  Методически правильная
последовательность написания курсовой работы следующая: сначала
пишется текст основной части, а затем введение, заключение, список
использованной литературы и приложения.  Все заимствования автора из
литературных, учебных и статистических источников должны иметь ссылки
на них в тексте работы.  Всего в курсовой работе должно быть
использовано не менее 20 источников.

** Защита
   :PROPERTIES:
   :CUSTOM_ID: defence
   :END:

Защиту курсовой работы принимает преподаватель, ведущими занятия по
соответствующему курсу.

Сданную курсовую работу в /исходном варианте/ рецензирует
преподаватель.  Сроком сдачи курсовой работы при этом считается дата
подачи этого варианта курсовой работы.  В рецензии на курсовую работу
он отмечает достоинства и недостатки работы, делает вывод о допуске
работы к защите и предлагает предварительную оценку.

Работа не допускается к защите:
1. по причине содержания, если:
   1. работа не носит самостоятельного характера;
   2. работа списана из литературных источников;
   3. не были раскрыты основные вопросы;
   4. вопросы не имеют логической связи или противоречат друг другу;
   5. в работе нет значимых выводов и авторских предложений;
   6. в тексте содержатся ошибочные положения.
2. по причине оформления, если:
   1. текст написан небрежно;
   2. текст содержит множество смысловых, стилистических и
      грамматических ошибок;
   3. более чем на 5 страниц нарушен объем работы (как в большую, так
      и в меньшую сторону).

Если работа не допущена к защите, то студент должен её в соответствии
с замечаниями и вновь представить руководителю, теперь уже в
/доработанном варианте/.  Менять тему курсовой работы в этот период не
разрешается.

Во время подготовки к защите студент продумывает логику своего
выступления и доказательств своих выводов и предложений.  Устное
выступление студента на защите занимает не более 5 минут, в ходе
которых студент должен обосновать, актуальность и цель работы,
поставленные и решенные в ней задачи, охарактеризовать полученные
выводы и рекомендации.  На основании дискуссии в течение не более 5
минут студент должен показать углубленное понимание вопросов, хорошее
владение материалом темы.

В выступлении следует сказать о тех исправлениях, которые были сделаны
в ходе работы над замечаниями рецензента, а также о тех замечаниях,
которые автору кажутся непонятными, или неверными.  На конкретные
замечания рецензента можно подготовить письменные ответы и
использовать их во время защиты, что дает возможность логически
стройно построить выступление.  Окончательная оценка формируется,
исходя из предварительной оценки работы научным руководителем, сроков
защиты и на основе устной защиты курсовой работы.  Она записывается
руководителем в зачетную книжку студента и в экзаменационную
ведомость.  Студенты, не успевшие защитить работу, к экзамену не
допускаются.

* Правила оформления курсовой работы
  :PROPERTIES:
  :CUSTOM_ID: typography
  :END:

Объем курсовой работы составляет 25--30 стандартных листов формата А4
(210×297 мм), набранных через 1.5 интервала шрифтом 14 pt.  Каждая
страница кроме титульного листа нумеруется.  Все листы работы должны
быть скреплены.

Следующие заголовки печатаются с новой страницы прописными буквами и
выравниваются по центру:
- введение;
- заголовки глав;
- заключение;
- список литературы;
- приложение.

Все остальные заголовки подразделов набираются строчными буквами
полужирным шрифтом.  Абзацный отступ должен быть не менее 1 см.
Заголовки должны четко и кратко отражать содержание глав.

Каждая глава должна состоять из 2-3-х подглав с заголовками,
обозначенными арабскими цифрами 1.1, 1.2, 1.3, 2.1, 2.2, 2.3 и т. д.

На титульном листе курсовой работы указываются:
- реквизиты организации:
  - наименование вышестоящей организации;
  - наименование центра;
- тема курсовой работы;
- реквизиты студента:
  - факультет, курс, группа;
  - фамилия, имя и отчество студента;
- реквизиты преподавателя:
  - должность, ученая степень;
  - фамилия и инициалы руководителя.

Затем следует оглавление с указанием номеров страниц введения,
разделов, глав, параграфов, заключения, списка использованной
литературы и приложений.

В ссылках должны быть отражены цитируемые или использованные материалы
из монографий, журнальных статей, справочников, учебных пособий.
Ссылки могут выглядеть, например, на первый использованный источник:
[1] или [2, с. 85].  Они указываются обычно в конце предложений.  В
список литературы включаются все источники, на которые имеются ссылки
и сноски в тексте и в приложениях.  Дважды или трижды один и тот же
источник указывать в списке нельзя.  Ссылаться на один и тот же
источник можно несколько раз, но всегда на первоначальный номер, под
которым источник упомянут был в первый раз.

Научный аппарат курсовой работы должен содержать весь использованный
объем литературы, статистического и фактического материала, а также
графики, таблицы, рисунки, разработанные или использованные студентом
при написании работы.  Все приведенные в работе рисунки, графики,
схемы, диаграммы, таблицы, формулы должны иметь сквозную нумерацию и
заголовки, после которых в скобках указывается номер источника в
списке литературы и страница.  Например, "[5, с. 16]" или "разработано
автором по данным [5, с. 56; 14, с.69]".

Графики, схемы, диаграммы обозначаются как рисунки.  Пример оформления
подписи под рисунком: "Рисунок 1 — Динамика доли малого бизнеса в
ВВП".

Правила оформления таблиц следующие: в правом верхнем углу перед
заголовком пишется: Таблица 1 (или 2 и т. д.)  Затем в следующей
строке дается заголовок таблицы.  В может быть указан источник и
страницы.  Дальше приводится сама таблица.

Оформление приложений аналогично оформлению таблиц: каждое приложение
должно иметь порядковый номер, заголовок и ссылку на источник, из
которого оно заимствовано.

Размер шрифта заголовков таблиц и цифрового материала может быть
уменьшен на один размер от основного текста.

Формулы выносятся в отдельную строку и нумеруются арабскими цифрами в
круглых скобках с правой стороны листа на уровне правого поля и
написанной формулы.

Список использованной литературы оформляется на основе ссылок, типа
[1, с. 121].  Здесь литература располагается в том же порядке, в
котором на нее были сделаны ссылки.  Если первая ссылка сделана на
"Экономическая теория. Макроэкономика. Часть 3 / Под
ред. А. А. Нестерова. – Самара, 2007. – 226 с.", то список должен
начинаться с этого учебного пособия с указанием полного количества
страниц.  Он обозначается под номером 1.

* Литература
  :PROPERTIES:
  :CUSTOM_ID: biblio
  :END:

1. Гражданский кодекс Российской Федерации, 1997.
2. Методические рекомендации по разработке инвестиционной политики
   предприятия. Утверждены приказом Минэкономики РФ от 01.10.1997
   №118.
3. Положение по ведению бухгалтерского учета ПБУ 17/02 «Учет расходов
   на научно-исследовательские, опытно-конструкторские и
   технологические работы». Утверждено приказом Минфина РФ от
   19.11.2002 №115н.
4. Авсянников Н. П. Инновационный менеджмент : Учеб. пособие. --- М.:
   Изд-во РУНД, 2002. --- 231 с.
5. Антикризисное управление: Учебник для вузов / Под
   ред. Э. М. Короткова. --- М.: Инфра-М, 2000. --- 267 с.
6. Балабанов И. Т. Инновационный менеджмент. --- СПб.:
   Питер, 2001. --- 304 с.
7. Круглова Н. Ю. Инновационный менеджмент: Учеб. пособие. --- 2-е
   изд., доп. --- М.: Издательство РДП, 2001. --- 352 с.
8. Морозов Ю. П. Инновационный менеджмент: Учеб. пособие для
   вузов. --- М.: ЮНИТИ-ДАНА, 2000. --- 446 с.
9. Мухамедьяров А. М. Инновационный менеджмент: Учеб. пособие. --- М.:
   ИНФРА-М, 2006. --- 127 с.
10. Основы инновационного менеджмента: Теория и практика:
    Учеб. пособие / Под ред. П. Н. Завлина и др. --- М.: ОАО «НПО»
    Издательство «Экономика», 2000. --- 475 с.
11. Переходов В. Н. Основы управления инновационной деятельностью. ---
    М.: ИНФРА-М, 2005. --- 222 с.
12. Фатхутдинов Р.А. Инновационный менеджмент: Учебник. --- 4-е
    изд. --- Спб.:Питер, 2003. --- 400 с.
13. Швандер В. А., Горфинкель В. Я. Инновационный менеджмент:
    Учебник. --- М.: Вузовский учебник, 2005. --- 382 с.

* Перечень тем
  :PROPERTIES:
  :CUSTOM_ID: themes
  :END:

Ниже приведены шаблоны тем для выполнения курсовых работ.  К каждой
теме приведены пункты, которые рекомендуется рассмотреть в курсовой
работе.

1. Роль и влияние инноваций на развитие предприятий в современных
   условиях
   - Нормативно-правовое регулирование инновационной деятельности
   - Понятие и сущность инноваций.  Классификация инноваций
   - Инновации как объект управления.  Жизненный цикл инноваций
     (наука-производство-потребление)
2. Развитие инновационной деятельности на предприятии
   - Развитие и современное состояние инновационного менеджмента
   - Особенности процесса управления инновационной деятельностью
   - Концептуальная модель управления инновациями: ориентация на рынок
3. Значение инновационных предприятий на развитие инновационного
   процесса и особенности их функционирования
   - Сущность организации инновационного предприятия и их
     классификация
   - Формирование новых прогрессивных организационных форм в
     инновационной деятельности
   - Подходы к проектированию инновационных предприятий
4. Особенности и совершенствование управления персоналом на
   инновационном предприятии
   - Цель инновационного проекта и его идея
   - Характеристика кадров, участвующих в инновационном процессе
   - Проектирование организационной структуры инновационного
     коллектива
5. Влияние мотивации творческого коллектива на инновационный
   менеджмент
   - Понятие и сущность мотивации в инновационном менеджменте
   - Современные теории мотивации
   - Особенности мотивации научно-технических работников
6. Особенности системы управления инновационным процессом на
   предприятии
   - Понятие и сущность инновационного процесса
   - Стадии, сферы и этапы инновационного цикла
     (наука-производство-потребление)
   - Влияние и характер инвестиций в инновационные процессы
   - Особенности системы управления инновационным процессом на
     предприятии
7. Разработка и совершенствование организационной структуры
   инновационного предприятия
   - Нормативно-правовое регулирование инновационной деятельности
   - Виды организационных структур инновационного предприятия
   - Особенности построения организационных структур инновационного
     предприятия
8. Разработка процесса реализации стратегических инновационных решений
   на предприятии
   - Роль стратегического управления в инновационной деятельности
   - Факторы, влияющие на выбор стратегии инноваций
   - Необходимость и условия применения стратегического планирования
9. Совершенствование организации инновационного менеджмента на
   предприятии <<modern>>
   - Сущность и особенности организации инновационного менеджмента
   - Формирование цели инновационной деятельности
   - Значение стратегического прогнозирования и планирования инноваций
   - Концептуальная модель управления инновациями: ориентация на рынок
10. Влияние рыночного механизма на реализацию нового товара (услуги)
    - Рыночный механизм как фактор продвижения нового товара
    - Основные формы маркетинговых исследований рынка новшеств
    - Влияние инноваций на качество и конкурентоспособность продукции
    - Рынок новшеств как источник инновационных предложений
11. Роль малых инновационных предприятий и новых прогрессивных
    организационных форм в развитии инновационной деятельности
    - Роль малого предпринимательства в развитии инновационной
      деятельности. Разновидности малых предприятий
    - Значение новых прогрессивных организационных форм в
      инновационной политике
    - Государственное регулирование деятельности малых инновационных
      предприятий и новых прогрессивных организационных форм в России
12. <<res-dist>> Распределение и использование финансовых ресурсов на
    инновационном предприятии
    - Роль инвестиций в инновационном процессе
    - Источники финансирования инновационной деятельности
    - Влияние методов государственного воздействия на уровень развития
      инновационной деятельности
13. Разработка инновационного проекта: содержание и процесс создания
    новшества
    - Понятие и основные элементы инновационного проекта
    - Виды и содержание инновационных проектов
    - Порядок разработки инновационного проекта
14. <<innov-control>> Организация контроля за выполнением инновационной программы
    - Система менеджмента инновационной программы
    - Этапы контроля за выполнением программы
    - Концептуальная модель управления инновациями: ориентация на
      рынок
15. <<gov-methods>> Методы государственного регулирования
    инновационных процессов
    - Инновационная политика государства
    - Основные меры государственного регулирования инновационных
      процессов
    - Зарубежный опыт управления инновационной деятельностью
16. <<dev-innov-manag>> Развитие и современное состояние
    инновационного менеджмента на предприятии
    - Экономическая сущность инновационного менеджмента
    - Современные подходы к развитию инновационного менеджмента
    - Особенности процесса управления инновационной деятельностью
    - Концептуальные модели управления инновациями
17. <<bplan>> Бизнес-план инновационной программы
    - Экономическое значение и понятие бизнес-плана инновационной
      программы (проекта) и основное его назначение
    - Порядок разработки бизнес-плана
    - Выбор бизнес-плана для реализации
    - Методы реализации бизнес-плана инновационного проекта
18. Особенности стратегического управления на инновационном
    предприятии
    - Роль стратегического управления инновациями
    - Факторы, влияющие на выбор стратегии инноваций
    - Необходимость и условия применения стратегического планирования
19. Механизм стратегического управления в инновационной деятельности
    - Научно-техническая политика государства и ее связь со стратегией
      развития экономики
    - Необходимость и условия применения стратегического планирования
    - Процесс принятия стратегических инновационных решений
    - Модель управления инновациями, ориентация на рынок
20. Новые подходы к управлению инновациями на предприятии
    - Экономическая сущность инновационного менеджмента
    - Современные подходы к развитию инновационного менеджмента
    - Особенности процесса управления инновационной деятельностью
    - Концептуальные модели управления инновациями
21. Особенности управления рисками в инновационной деятельности
    - Экономическое значение рисков и их классификация
    - Этапы процесса управления рисками
    - Оценка и оптимизация уровня рисков в инновационной деятельности
    - Методы управления рисками

* Список изменений

- [2019-02-21 Чт] :: (1.0.0) Черновик завершен; используется в учебном
     процессе
- [2019-04-16 Вт] :: (1.1.0) Добавлен процесс защиты реферата

