#+TITLE: Основные требования к курсовой работе

Курсовая работа представляет собой разработку актуальной теоретической
или практической экономической проблемы.  В ней должны быть отражены
позиции российских и зарубежных экономистов, периодическая научная
литература, статистическая информация, материалы, взятые из сети
Internet.

Перед выполнением работы студент составляет план.  План служит опорой
и перечнем тем, которые студенту нужно раскрыть в ходе выполнения
курсовой работы.  Студент самостоятельно или консультируясь с
руководителем подбирает основную и дополнительную литературу,
определить те важнейшие публикации, которые будут положены в основу
курсовой работы и наиболее полно раскрывают тему.

Тема курсовой работы раскрывается на основе изучения современной
научной и учебной экономической литературы, журнальных и газетных
публикаций, статистических материалов.  Хотя отдельные главы и
параграфы курсовой работы могут совпадать с названием некоторых
параграфов соответствующих научных изданий или разделов учебников,
работа не должна быть пересказом материала, изложенного в литературе.

Не допускается дословное заимствование (списывание) текста.  Дословное
копирование литературы противоречит смыслу курсовой работы, не
способствует получению практических знаний и умений, приучает студента
к бездумному повторению известных истин.  Поэтому текст курсовой
работы должен быть написан самостоятельно в соответствии с планом.  В
работе должны содержаться элементы творчества, теоретические положения
должны быть связаны с практикой хозяйствования и реформирования
экономики.

В ходе написания работы студент изучает правила оформления научного
аппарата, грамотного применения сносок, ссылок на источники информации
и правил оформления списка литературы или библиографического списка.

Если в литературе по теме работы имеются различные точки зрения или
представлены различные методы решения той или иной проблемы, студент
должен обосновать свою позицию, которая, не обязательно должна
совпадать с чьим-то мнением.  При этом желательно, чтобы студент
продемонстрировал практическое подтверждение своей точки зрения.
Курсовая работа показывает способность студента самостоятельно
мыслить, творчески относиться к литературным источникам, формулировать
выводы и предложения, основанные на анализе фактического материала.
